cache:
  pip: true
  directories:
    - $HOME/releng-tool-cache
    - $HOME/releng-tool-dl

matrix:
  include:
    # minimal example
    - os: linux
      env: ROOT_DIR=minimal
      language: python
      python: '2.7'
    - os: linux
      env: ROOT_DIR=minimal
      language: python
      python: '3.4'
    - os: linux
      env: ROOT_DIR=minimal
      language: python
      python: '3.5'
    - os: linux
      env: ROOT_DIR=minimal
      language: python
      python: '3.6'
    - os: linux
      env: ROOT_DIR=minimal
      language: python
      python: '3.7'
      dist: xenial
    - os: osx
      env: ROOT_DIR=minimal
      language: minimal
      before_install:
        - python2 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
    - os: osx
      env: ROOT_DIR=minimal
      language: minimal
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
    - os: windows
      env: ROOT_DIR=minimal
      language: sh
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv
        - venv/Scripts/activate.bat
    - os: windows
      env: ROOT_DIR=minimal
      language: sh
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv
        - venv/Scripts/activate.bat

    # bzr example
    - os: linux
      env: ROOT_DIR=bzr
      language: generic
      dist: xenial
      before_install:
        - sudo python -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python
        - source venv/bin/activate

    # git example
    - os: linux
      env: ROOT_DIR=git
      language: generic
      dist: xenial
      before_install:
        - sudo python -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python
        - source venv/bin/activate

    # nghttp2 example
    - os: linux
      env: ROOT_DIR=nghttp2
      language: generic
      dist: bionic
      before_install:
        - sudo python -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python
        - source venv/bin/activate

install:
  - pip install git+https://github.com/releng-tool/releng-tool.git

before_script:
  - python --version
  - env | sort

script:
  - |
      releng-tool \
        --root-dir $ROOT_DIR \
        --cache-dir $HOME/releng-tool-cache \
        --dl-dir $HOME/releng-tool-dl \
        --debug \
        --jobs 1

after_script:
  - find $ROOT_DIR/output/target 2>/dev/null

notifications:
  email: false
