#!/usr/bin/env python
# -*- coding: utf-8 -*-

LIBJEMALLOC_INSTALL_TYPE = 'staging'
LIBJEMALLOC_LICENSE = ['BSD-2-Clause']
LIBJEMALLOC_LICENSE_FILES = ['COPYING']
LIBJEMALLOC_SITE = 'https://github.com/jemalloc/jemalloc/releases/download/5.1.0/jemalloc-5.1.0.tar.bz2'
LIBJEMALLOC_TYPE = 'autotools'
LIBJEMALLOC_VERSION = '5.1.0'

LIBJEMALLOC_CONF_DEFS = {
}
