name: Examples

on:
  workflow_dispatch:
    inputs:
      root_target:
        description: 'Root target to run'

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
            # minimal examples on each python interpreter
            - { os: ubuntu-latest, python:  "2.7", root_dir: minimal, cache: ~/.cache/pip }
            - { os:  ubuntu-20.04, python:  "3.5", root_dir: minimal, cache: ~/.cache/pip }
            - { os:  ubuntu-20.04, python:  "3.6", root_dir: minimal, cache: ~/.cache/pip }
            - { os: ubuntu-latest, python:  "3.7", root_dir: minimal, cache: ~/.cache/pip }
            - { os: ubuntu-latest, python:  "3.8", root_dir: minimal, cache: ~/.cache/pip }
            - { os: ubuntu-latest, python:  "3.9", root_dir: minimal, cache: ~/.cache/pip }
            - { os: ubuntu-latest, python: "3.10", root_dir: minimal, cache: ~/.cache/pip }
            - { os: ubuntu-latest, python: "3.11", root_dir: minimal, cache: ~/.cache/pip }

            # minimal examples on additional operating systems
            - { os:   macos-latest, python:  "2.7", root_dir: minimal, cache: ~/Library/Caches/pip }
            - { os:   macos-latest, python: "3.11", root_dir: minimal, cache: ~/Library/Caches/pip }
            - { os: windows-latest, python:  "2.7", root_dir: minimal, cache: ~\AppData\Local\pip\Cache }
            - { os: windows-latest, python: "3.11", root_dir: minimal, cache: ~\AppData\Local\pip\Cache }

            # bzr example
            - { os: ubuntu-latest, python: "3.11", root_dir: bzr, cache: ~/.cache/pip }

            # git example
            - { os: ubuntu-latest, python: "3.11", root_dir: git, cache: ~/.cache/pip }

            # gpsd example
            - { os: ubuntu-latest, python: "3.11", root_dir: gpsd, cache: ~/.cache/pip }

            # libiconv example
            - { os: ubuntu-latest, python: "3.11", root_dir: libiconv, cache: ~/.cache/pip, action: extract }

            # mercurial-hello example
            - { os: ubuntu-latest, python: "3.11", root_dir: mercurial-hello, cache: ~/.cache/pip }

            # pacman example
            - { os: ubuntu-latest, python: "3.11", root_dir: pacman, cache: ~/.cache/pip }

            # nghttp2 example
            - { os: ubuntu-latest, python: "3.11", root_dir: nghttp2, cache: ~/.cache/pip }

            # vulkan-samples example
            - { os:  ubuntu-latest, python: "3.11", root_dir: vulkan-samples, cache: ~/.cache/pip }
            - { os: windows-latest, python: "3.11", root_dir: vulkan-samples, cache: ~\AppData\Local\pip\Cache }

    steps:
    - name: Check if matrix job is permitted
      # If a specific project has been requested, only run for the requested root.
      if: ${{ github.event.inputs.root_target != '' && github.event.inputs.root_target != matrix.root_dir }}
      run: |
        echo ${{ github.event.inputs.root_target }}
        exit 1

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Cache
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: |
            ${{ matrix.cache }}
            $HOME/releng-tool-cache
            $HOME/releng-tool-dl
        key: ${{ matrix.os }}-${{ matrix.python }}-pip

    # dependencies
    - name: Install dependencies (Python)
      run: >
        python -m pip install --upgrade
        matplotlib
        pip
        wheel
    # dependencies (bzr)
    - name: Install dependencies (bzr; ubuntu-latest)
      run: >
        sudo apt-get install
        bzr
        python2-dev
      if: matrix.os == 'ubuntu-latest' && matrix.root_dir == 'bzr'
    # dependencies (libiconv)
    - name: Install dependencies (libiconv; ubuntu-latest)
      run: >
        sudo apt-get install
        cvs
      if: matrix.os == 'ubuntu-latest' && matrix.root_dir == 'libiconv'
    # dependencies (git)
    - name: Install dependencies (git; ubuntu-latest)
      run: >
        sudo apt-get install
        gettext
      if: matrix.os == 'ubuntu-latest' && matrix.root_dir == 'git'
    # dependencies (mercurial-hello)
    - name: Install dependencies (mercurial-hello; ubuntu-latest)
      run: >
        sudo apt-get install
        mercurial
      if: matrix.os == 'ubuntu-latest' && matrix.root_dir == 'mercurial-hello'
    # dependencies (pacman)
    - name: Install dependencies (pacman; ubuntu-latest).
      # libarchive public key
      run: gpg --recv-keys DB2C7CF1B4C265FAEF56E3FC5848A18B8F14184B
      run: >
        sudo apt-get install
        ninja-build
      if: matrix.os == 'ubuntu-latest' && matrix.root_dir == 'pacman'
    # dependencies (vulkan-samples)
    - name: Install dependencies (vulkan-samples; ubuntu-latest)
      run: >
        sudo apt-get install
        libwayland-dev
      if: matrix.os == 'ubuntu-latest' && matrix.root_dir == 'vulkan-samples'

    - name: Install releng-tool
      run: python -m pip install git+https://github.com/releng-tool/releng-tool.git

    - name: State information
      run: |
        python --version
        env | sort

    - name: Build test
      run: >
        releng-tool
        --root-dir ${{ matrix.root_dir }}
        --cache-dir $HOME/releng-tool-cache
        --dl-dir $HOME/releng-tool-dl
        --debug
        ${{ matrix.action }}

    - name: Dump of output
      run: |
        find ${{ matrix.root_dir }}/output/target 2>/dev/null || true
        find ${{ matrix.root_dir }}/output/images 2>/dev/null || true
      if: matrix.os != 'windows-latest'

    - name: Dump of output
      run: |
        Get-ChildItem ${{ matrix.root_dir }}/output/target -recurse | foreach fullname
        Get-ChildItem ${{ matrix.root_dir }}/output/target -recurse | foreach fullname
      if: matrix.os == 'windows-latest'

    - name: Track duration information
      uses: actions/upload-artifact@v2
      with:
        name: durations-${{ matrix.root_dir }}-${{ matrix.os }}-${{ matrix.python }}
        path: ${{ matrix.root_dir }}/output/misc/durations*
